{% set version = "2.3.4" %}

{% set posix = 'm2-' if win else '' %}

package:
  name: r-r2html
  version: {{ version|replace("-", "_") }}

source:
  fn: R2HTML_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/R2HTML_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/R2HTML/R2HTML_{{ version }}.tar.gz
  sha256: b9ed93a48840e7866ccfec7948c62b0c3708915865d79f851eb0bde27af21ea9

build:
  noarch: generic
  number: 1

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base

  run:
    - r-base

test:
  commands:
    - $R -e "library('R2HTML')"  # [not win]
    - "\"%R%\" -e \"library('R2HTML')\""  # [win]

about:
  home: https://github.com/nalimilan/R2HTML
  license: GPL (>= 2)
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
  summary: Includes HTML function and methods to write in an HTML file. Thus, making HTML reports is easy. Includes a function that allows redirection on the fly, which appears to be very useful for teaching purpose, as the student can keep a copy of the produced output to keep all that he did during the course. Package
    comes with a vignette describing how to write HTML reports for statistical analysis. Finally, a driver for 'Sweave' allows to parse HTML flat files containing R code and to automatically write the corresponding outputs (tables and graphs).
  license_family: GPL3

extra:
  recipe-maintainers:
    - conda-forge/r
