appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: B5HgiohQu3bsk60kIurAdp29H5J9K2poE4629wCz2kloegq89mWzapk7Jujpb7c7CCuk8mHIqQILb8Rj4U/yMahkJqPRnjJDASNG9PO1bzL6Ueg57jmIezlelW6PLY+cX0mjDrEjGlHXFYMAIfJWs9GMq7ZoWOaQBLV2OeTaM1MXfI86v6i14k9RLmPuUXBDUr1nyJxUO0nolKBfRVCGk7b0IIEEr/8XZrB0ayDkalH6u9GvWVTvNBFM3Roig7CesLZnzziMp7pUS0oZngU6GXWwh/pLZP6J0ax5JK+TQHh86OwXLz6femPJC3EokZ28PjzBAdJ1lhpcOUZVbwUzGsuQaYYPSgUvG0rAdqEPZo1U/gnHtOGuNr5rXajArNhC3AIW0Is3s9UJCT/Qsa9yzNf4uFMFeXYyb/3hMbpnGZ2EXFROf+fQirsYk4CyTXJNosnQuOSW/TtNhth93asyQXsn25OoLjTx9mrxGojazE8Tb8FKsRs22wOketi0PqCEyUeV4MdXNg1/OxfnNX7w63RYN8Kj9G3uwHKkHO9o4z+qHxF2IUowGklqEW0Pvs9i1Fwn/2MQDeL6Hqcas/tzIG0v+w4tWLPa/o8u+SmoLIX/63ti/uz6/a6BCM+nqnmNKDFNAqyoNFNKqLp1SnDEdKTqz2vlxhQly03jef2qfsM=}
