travis:
  secure:
    BINSTAR_TOKEN: TbtqqriUTlJz17Iq3vPyy7BjTllIH/XRQbvDIlzEiZtZeDn5MQkuABQMpqTJQfozGwqK2CtXLVD4N//7G3kJ+XQG0g/9zStE2mPzQ0ON5MknhQoUJiMS9P6aELtFc8l3BU/HBlzcjeHJDK8vh2GiWHvQcSQc7rXaEMBj6RQG3qA6lq5r8kAvmn8vrFIof4vJ35Fz5QEj/MOni+X7RBWGw/sn6tm9zADOvlmh0OYsp1gA3voMTMN5zt8bWc2q1pCRgRcr7Hdy/EOlxYUSj4aiwuaa6ZBW0wz3BM85VI+5KdYVyLx6JSqdCFCBU4lMui+3HURnKBAZH6Zdp7OetoT/JwFvcvC4ikZUCslyIMfYTeFBdLesBFx4Hnrb7cipUZThKKo3lXtFq3XwcKnydcHz9Bn6VKjhbWVuO/wakauzVTaPfPRm2zj7WUwMbMTbFBv3zZQ/8NERedKj7L3j+dD/BOj/l5To5vr2rbBDSkmqVqyrsuEO/mdrkIThtbc4zKHMjHFJs7SnwBJJKNkV3HrDc4bTM28h9yIXdx/jpYZR7+UmudYKXEqRSimv5Q/8TPmmrkO47oNOyRTvrWM1sBoBKII4KhdSpi9+69ggJFDTPU7SOYVPsfOK6XRGqMLEGaAeEuM4pbW4G439k/Z+ec3UhTMRngcnA/xFyH0qYqs1mAo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
